default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: closedsales_development

test: &test
  <<: *default
  database: closedsales_test

demo:
  <<: *default
  database: closedsales_demo

production:
  <<: *default
  database: closedsales_production

cucumber:
  <<: *test